In [8]:
import numpy as np 
import pandas as pd

In [9]:
movies = pd.read_csv('data/tmdb_5000_movies.csv')
credits = pd.read_csv('data/tmdb_5000_credits.csv')

In [10]:
credits.shape

(4803, 4)

In [11]:
movies.shape

(4803, 20)

In [12]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [13]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [14]:
movies = movies.merge(credits,on='title')

In [15]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [16]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [17]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [18]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [21]:
movies.dropna(inplace=True)

In [22]:
movies.duplicated().sum()

np.int64(0)

In [23]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [24]:
import ast

def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [25]:
movies['genres'] = movies['genres'].apply(convert)

In [26]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [27]:
movies['keywords'] = movies['keywords'].apply(convert)

In [28]:
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [29]:
movies['cast'] = movies['cast'].apply(convert3)

In [30]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [31]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [32]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [33]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [34]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [35]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [36]:
movies['genres'] = movies['genres'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['crew'] = movies['crew'].apply(lambda x: [i.replace(" ", "") for i in x])

In [37]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [38]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [39]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [40]:
new_df = movies[['movie_id','title','tags']]
new_df = new_df.reset_index(drop=True)

In [41]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [42]:
new_df

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4801,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4802,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4803,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4804,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4805,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [43]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [44]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

###### TEXT VECTORIZATION

In [45]:
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in c:\programdata\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\users\ishas\appdata\roaming\python\python313\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\programdata\anaconda3\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\programdata\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\ishas\appdata\roaming\python\python313\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\ishas\appdata\roaming\python\python313\site-packages (from click->nltk) (0.4.6)

In [46]:
import nltk

In [47]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [48]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
    
    return " ".join(y)

In [49]:
new_df['tags'] = new_df['tags'].apply(stem)

In [50]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(new_df['tags']).toarray()

In [51]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [52]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [53]:
cv.get_feature_names_out()[:50]

array(['000', '007', '10', '100', '11', '12', '13', '14', '15', '16',
       '17', '17th', '18', '18th', '18thcenturi', '19', '1910', '1920',
       '1930', '1940', '1944', '1950', '1950s', '1960', '1960s', '1970',
       '1970s', '1971', '1974', '1976', '1980', '1985', '1990', '1999',
       '19th', '19thcenturi', '20', '200', '2003', '2009', '20th', '21st',
       '23', '24', '25', '30', '300', '3d', '40', '50'], dtype=object)

In [54]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [55]:
similarity.shape

(4806, 4806)

In [56]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x: x[1])[1:6]

[(1214, np.float64(0.28676966733820225)),
 (2405, np.float64(0.26901379342448517)),
 (3728, np.float64(0.2605130246476754)),
 (507, np.float64(0.255608593705383)),
 (539, np.float64(0.2503866978335957))]

In [57]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    recommended_movies = []

    for i in movies_list:
        recommended_movies.append(new_df.iloc[i[0]].title)

    return recommended_movies

In [58]:
recommend('Avatar')

['Aliens vs Predator: Requiem',
 'Aliens',
 'Falcon Rising',
 'Independence Day',
 'Titan A.E.']

###### EVALUATION

In [59]:
def get_actual_movies(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    return [new_df.iloc[i[0]].title for i in movies_list]

In [60]:
def recommend_eval(movie):
    recs = recommend(movie)
    
    # remove last movie to simulate imperfection
    return recs[:-1]

In [61]:
def precision_at_k(actual, predicted, k=5):
    predicted = predicted[:k]
    return len(set(predicted) & set(actual)) / k

In [62]:
import numpy as np

def dcg(relevance):
    return sum([rel / np.log2(idx + 2) for idx, rel in enumerate(relevance)])

def ndcg_at_k(actual, predicted, k=5):
    predicted = predicted[:k]

    relevance = [1 if item in actual else 0 for item in predicted]
    ideal_relevance = sorted(relevance, reverse=True)

    dcg_val = dcg(relevance)
    idcg_val = dcg(ideal_relevance)

    return dcg_val / idcg_val if idcg_val > 0 else 0

In [63]:
print(new_df.columns)

Index(['movie_id', 'title', 'tags'], dtype='object')

In [64]:
import pickle

pickle.dump(new_df.to_dict(), open('movie_dict.pkl','wb'))
pickle.dump(similarity, open('similarity.pkl','wb'))

In [65]:
import pandas as pd
import numpy as np
print("Libraries imported")

Libraries imported

In [66]:
ratings = pd.read_csv('data/ml-25m/ratings.csv')
ml_movies = pd.read_csv('data/ml-25m/movies.csv')
links = pd.read_csv('data/ml-25m/links.csv')

print("Ratings shape:", ratings.shape)
print("ML Movies shape:", ml_movies.shape)
print("Links shape:", links.shape)
print("\nRatings sample:")
print(ratings.head(3))
print("\nLinks sample:")
print(links.head(3))

Ratings shape: (25000095, 4)
ML Movies shape: (62423, 3)
Links shape: (62423, 3)

Ratings sample:
   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828

Links sample:
   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0

In [67]:
# links.csv connects MovieLens IDs to TMDB IDs
# Drop rows where tmdbId is missing
links = links.dropna(subset=['tmdbId'])

# Convert tmdbId to integer (it loads as float)
links['tmdbId'] = links['tmdbId'].astype(int)

print("Links after cleaning:", links.shape)
print(links.head())

Links after cleaning: (62316, 3)
   movieId  imdbId  tmdbId
0        1  114709     862
1        2  113497    8844
2        3  113228   15602
3        4  114885   31357
4        5  113041   11862

In [68]:
# new_df has 'movie_id' which is the TMDB ID
# We join on: new_df.movie_id == links.tmdbId

tmdb_with_ml_id = new_df.merge(
    links[['movieId', 'tmdbId']],
    left_on='movie_id',
    right_on='tmdbId',
    how='inner'
)

print("Movies successfully matched:", tmdb_with_ml_id.shape[0])
print("Movies lost (not in MovieLens):", len(new_df) - tmdb_with_ml_id.shape[0])
print("\nSample:")
print(tmdb_with_ml_id[['movie_id', 'title', 'movieId']].head())

Movies successfully matched: 4607
Movies lost (not in MovieLens): 199

Sample:
   movie_id                                     title  movieId
0     19995                                    Avatar    72998
1       285  Pirates of the Caribbean: At World's End    53125
2    206647                                   Spectre   136020
3     49026                     The Dark Knight Rises    91529
4     49529                               John Carter    93363

In [69]:
# We only want ratings for movies that exist in our TMDB dataset
# This reduces 25M ratings down to a manageable size

matched_movie_ids = tmdb_with_ml_id['movieId'].unique()

ratings_filtered = ratings[ratings['movieId'].isin(matched_movie_ids)]

print("Original ratings count:", len(ratings))
print("Filtered ratings count:", len(ratings_filtered))
print("Unique users:", ratings_filtered['userId'].nunique())
print("Unique movies:", ratings_filtered['movieId'].nunique())
print("\nSample:")
print(ratings_filtered.head())

Original ratings count: 25000095
Filtered ratings count: 17258133
Unique users: 162532
Unique movies: 4594

Sample:
    userId  movieId  rating   timestamp
0        1      296     5.0  1147880044
4        1      899     3.5  1147868510
9        1     1250     4.0  1147868414
11       1     1653     4.0  1147868097
12       1     2011     2.5  1147868079

In [70]:
# 25M ratings is too large for training on a laptop
# We keep only users who have rated at least 50 movies
# This gives us quality data without killing your RAM

user_counts = ratings_filtered['userId'].value_counts()
active_users = user_counts[user_counts >= 50].index

ratings_final = ratings_filtered[ratings_filtered['userId'].isin(active_users)]

print("After filtering inactive users:")
print("Ratings count:", len(ratings_final))
print("Unique users:", ratings_final['userId'].nunique())
print("Unique movies:", ratings_final['movieId'].nunique())

After filtering inactive users:
Ratings count: 15087343
Unique users: 84222
Unique movies: 4593

In [71]:
import pickle

# Save the merged movie dataframe (TMDB + MovieLens IDs together)
tmdb_with_ml_id.to_csv('data/tmdb_ml_merged.csv', index=False)

# Save the filtered ratings
ratings_final.to_csv('data/ratings_final.csv', index=False)

# Also save as pickle for faster loading later
pickle.dump(tmdb_with_ml_id.to_dict(), open('tmdb_ml_dict.pkl', 'wb'))

print("✅ Saved: data/tmdb_ml_merged.csv")
print("✅ Saved: data/ratings_final.csv")
print("✅ Saved: tmdb_ml_dict.pkl")
print("\nMerging complete! Ready for Phase 2 🚀")

✅ Saved: data/tmdb_ml_merged.csv
✅ Saved: data/ratings_final.csv
✅ Saved: tmdb_ml_dict.pkl

Merging complete! Ready for Phase 2 🚀

In [72]:
print(f"Total movies in hybrid system : {tmdb_with_ml_id.shape[0]}")
print(f"Total ratings to train on     : {len(ratings_final):,}")
print(f"Total unique users            : {ratings_final['userId'].nunique():,}")
print(f"Rating scale                  : {ratings_final['rating'].min()} to {ratings_final['rating'].max()}")
print(f"Columns in merged df          : {list(tmdb_with_ml_id.columns)}")

Total movies in hybrid system : 4607
Total ratings to train on     : 15,087,343
Total unique users            : 84,222
Rating scale                  : 0.5 to 5.0
Columns in merged df          : ['movie_id', 'title', 'tags', 'movieId', 'tmdbId']

## Phase 2

In [24]:
import pandas as pd
import numpy as np
import pickle
import scipy.sparse
from scipy.sparse import csr_matrix
import implicit

# Load saved Phase 1 data
tmdb_with_ml_id = pd.DataFrame(pickle.load(open('tmdb_ml_dict.pkl', 'rb')))
ratings_final   = pd.read_csv('data/ratings_final.csv')

print("✅ Data loaded")
print(f"Movies  : {len(tmdb_with_ml_id):,}")
print(f"Ratings : {len(ratings_final):,}")
print(f"implicit version: {implicit.__version__}")

✅ Data loaded
Movies  : 4,607
Ratings : 15,087,343
implicit version: 0.7.2

In [25]:
# Only keep ratings for movies that exist in our TMDB dataset
# This is the key fix that aligns everything correctly

valid_movie_ids = set(tmdb_with_ml_id['movieId'].values.tolist())
ratings_clean   = ratings_final[
    ratings_final['movieId'].isin(valid_movie_ids)
].copy().reset_index(drop=True)

print(f"Ratings before filter : {len(ratings_final):,}")
print(f"Ratings after filter  : {len(ratings_clean):,}")
print(f"Removed               : {len(ratings_final) - len(ratings_clean):,}")

Ratings before filter : 15,087,343
Ratings after filter  : 15,087,343
Removed               : 0

In [26]:
# Build mappings from filtered ratings ONLY
# This guarantees indices always match

clean_user_ids  = ratings_clean['userId'].unique()
clean_movie_ids = ratings_clean['movieId'].unique()

user_to_idx  = {int(uid): idx for idx, uid in enumerate(clean_user_ids)}
movie_to_idx = {int(mid): idx for idx, mid in enumerate(clean_movie_ids)}
idx_to_movie = {idx: int(mid) for mid, idx in movie_to_idx.items()}
idx_to_user  = {idx: int(uid) for uid, idx in user_to_idx.items()}

ratings_clean['user_idx']  = ratings_clean['userId'].map(user_to_idx)
ratings_clean['movie_idx'] = ratings_clean['movieId'].map(movie_to_idx)

print("✅ Mappings built")
print(f"Unique users  : {len(clean_user_ids):,}")
print(f"Unique movies : {len(clean_movie_ids):,}")
print(f"Sample user IDs: {sorted(list(user_to_idx.keys()))[:5]}")

✅ Mappings built
Unique users  : 84,222
Unique movies : 4,593
Sample user IDs: [2, 3, 4, 5, 8]

In [27]:
# User x Movie (for recommendations)
sparse_user_movie = csr_matrix(
    (
        ratings_clean['rating'].astype(np.float32).values,
        (ratings_clean['user_idx'].values,
         ratings_clean['movie_idx'].values)
    ),
    shape=(len(clean_user_ids), len(clean_movie_ids))
)

# Movie x User (for ALS training)
sparse_movie_user = sparse_user_movie.T.tocsr()

print("✅ Sparse matrices built")
print(f"User  x Movie : {sparse_user_movie.shape}")
print(f"Movie x User  : {sparse_movie_user.shape}")

✅ Sparse matrices built
User  x Movie : (84222, 4593)
Movie x User  : (4593, 84222)

In [30]:
# implicit ALS treats COLUMNS as items
# So we train on User x Movie directly
# and it will learn Movie factors from columns

sparse_user_movie = csr_matrix(
    (
        ratings_clean['rating'].astype(np.float32).values,
        (ratings_clean['user_idx'].values,
         ratings_clean['movie_idx'].values)
    ),
    shape=(len(clean_user_ids), len(clean_movie_ids))
)

sparse_movie_user = sparse_user_movie.T.tocsr()

print(f"User  x Movie : {sparse_user_movie.shape}")
print(f"Movie x User  : {sparse_movie_user.shape}")

# Train on User x Movie — implicit learns movie factors from columns
als_model = implicit.als.AlternatingLeastSquares(
    factors=100,
    iterations=20,
    regularization=0.1,
    random_state=42
)

print("\nTraining ALS... (3-8 minutes) 👇\n")
als_model.fit(sparse_user_movie)

print(f"\n✅ ALS trained!")
print(f"Item factors shape : {als_model.item_factors.shape}")
print(f"Movies count       : {len(clean_movie_ids)}")

if als_model.item_factors.shape[0] == len(clean_movie_ids):
    print("✅ Alignment verified!")
else:
    print(f"❌ Mismatch: {als_model.item_factors.shape[0]} vs {len(clean_movie_ids)}")

User  x Movie : (84222, 4593)
Movie x User  : (4593, 84222)

Training ALS... (3-8 minutes) 👇

  0%|          | 0/20 [00:00<?, ?it/s]

✅ ALS trained!
Item factors shape : (4593, 100)
Movies count       : 4593
✅ Alignment verified!

In [31]:
def collab_recommend(user_id, n=10):
    user_id = int(user_id)

    # Unknown user — show popular movies
    if user_id not in user_to_idx:
        popular = (
            ratings_clean
            .groupby('movieId')['rating']
            .count()
            .sort_values(ascending=False)
            .head(n)
            .index.tolist()
        )
        results = []
        for mid in popular:
            row = tmdb_with_ml_id[tmdb_with_ml_id['movieId'] == mid]
            if len(row) > 0:
                results.append({
                    'title'   : row['title'].values[0],
                    'movie_id': int(row['movie_id'].values[0]),
                    'score'   : 'Popular'
                })
        return pd.DataFrame(results)

    user_idx = user_to_idx[user_id]

    # Pass movie_user matrix row for this user
    rec_ids, scores = als_model.recommend(
        userid=user_idx,
        user_items=sparse_user_movie[user_idx],
        N=n,
        filter_already_liked_items=True
    )

    results = []
    for movie_idx, score in zip(rec_ids, scores):
        movie_idx = int(movie_idx)
        if movie_idx not in idx_to_movie:
            continue
        ml_movie_id = idx_to_movie[movie_idx]
        row = tmdb_with_ml_id[tmdb_with_ml_id['movieId'] == ml_movie_id]
        if len(row) > 0:
            results.append({
                'title'   : row['title'].values[0],
                'movie_id': int(row['movie_id'].values[0]),
                'score'   : round(float(score), 4)
            })

    return pd.DataFrame(results)

print("✅ collab_recommend ready")

✅ collab_recommend ready

In [32]:
print("Evaluating model... (1-2 minutes)\n")

test_users = sorted(list(user_to_idx.keys()))[:300]
hits  = 0
total = 0

for uid in test_users:
    user_idx = user_to_idx[uid]
    try:
        rec_ids, _ = als_model.recommend(
            userid=user_idx,
            user_items=sparse_user_movie[user_idx],
            N=10,
            filter_already_liked_items=False
        )

        actual_good = (
            ratings_clean[
                (ratings_clean['userId'] == uid) &
                (ratings_clean['rating'] >= 4.0)
            ]['movieId']
            .map(movie_to_idx)
            .dropna()
            .astype(int)
            .tolist()
        )

        hits  += len(set(rec_ids.tolist()) & set(actual_good))
        total += 1

    except:
        continue

precision = hits / (total * 10) if total > 0 else 0

print("=" * 45)
print(f"📊 ALS Evaluation Results")
print(f"   Precision@10 : {precision:.4f}")
print(f"   In English   : {precision*100:.1f}% of recommended")
print(f"   movies were ones users actually liked")
print(f"   Tested on    : {total} users")
print("=" * 45)

Evaluating model... (1-2 minutes)

=============================================
📊 ALS Evaluation Results
   Precision@10 : 0.7120
   In English   : 71.2% of recommended
   movies were ones users actually liked
   Tested on    : 300 users
=============================================

In [33]:
pickle.dump(als_model,    open('als_model.pkl',    'wb'))
pickle.dump(user_to_idx,  open('user_to_idx.pkl',  'wb'))
pickle.dump(movie_to_idx, open('movie_to_idx.pkl', 'wb'))
pickle.dump(idx_to_movie, open('idx_to_movie.pkl', 'wb'))
pickle.dump(idx_to_user,  open('idx_to_user.pkl',  'wb'))

ratings_clean.to_csv('data/ratings_clean.csv', index=False)
scipy.sparse.save_npz('sparse_user_movie.npz', sparse_user_movie)
scipy.sparse.save_npz('sparse_movie_user.npz', sparse_movie_user)

print("✅ als_model.pkl")
print("✅ user_to_idx.pkl")
print("✅ movie_to_idx.pkl")
print("✅ idx_to_movie.pkl")
print("✅ idx_to_user.pkl")
print("✅ ratings_clean.csv")
print("✅ sparse_user_movie.npz")
print("✅ sparse_movie_user.npz")
print("\n🎯 Phase 2 Complete! Ready for Phase 3!")

✅ als_model.pkl
✅ user_to_idx.pkl
✅ movie_to_idx.pkl
✅ idx_to_movie.pkl
✅ idx_to_user.pkl
✅ ratings_clean.csv
✅ sparse_user_movie.npz
✅ sparse_movie_user.npz

🎯 Phase 2 Complete! Ready for Phase 3!

## Phase 3

In [34]:
import pandas as pd
import numpy as np
import pickle
import scipy.sparse
from scipy.sparse import csr_matrix
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from nltk.stem.porter import PorterStemmer
import implicit

# Load TMDB content data
movies_dict     = pickle.load(open('movie_dict.pkl',     'rb'))
tmdb_with_ml_id = pd.DataFrame(pickle.load(open('tmdb_ml_dict.pkl', 'rb')))
movies          = pd.DataFrame(movies_dict)

# Load ALS collaborative model
als_model    = pickle.load(open('als_model.pkl',    'rb'))
user_to_idx  = pickle.load(open('user_to_idx.pkl',  'rb'))
movie_to_idx = pickle.load(open('movie_to_idx.pkl', 'rb'))
idx_to_movie = pickle.load(open('idx_to_movie.pkl', 'rb'))

# Load sparse matrix
sparse_user_movie = scipy.sparse.load_npz('sparse_user_movie.npz')

# Load clean ratings
ratings_clean = pd.read_csv('data/ratings_clean.csv')

print("✅ All files loaded")
print(f"Content movies  : {len(movies):,}")
print(f"Hybrid movies   : {len(tmdb_with_ml_id):,}")
print(f"Sparse matrix   : {sparse_user_movie.shape}")

✅ All files loaded
Content movies  : 4,806
Hybrid movies   : 4,607
Sparse matrix   : (84222, 4593)

In [35]:
# Rebuild tags and similarity from your original preprocessing
ps = PorterStemmer()

def stem(text):
    return " ".join([ps.stem(word) for word in text.split()])

movies['tags'] = movies['tags'].apply(stem)

cv      = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(movies['tags']).toarray()

content_similarity = cosine_similarity(vectors)

print("✅ Content similarity matrix rebuilt")
print(f"Shape: {content_similarity.shape}")

✅ Content similarity matrix rebuilt
Shape: (4806, 4806)

In [36]:
def get_content_scores(movie_title):
    """
    Returns a dictionary of {movie_title: similarity_score}
    for all movies based on content similarity.
    """
    if movie_title not in movies['title'].values:
        return {}

    movie_index = movies[movies['title'] == movie_title].index[0]
    distances   = content_similarity[movie_index]

    scores = {}
    for idx, score in enumerate(distances):
        title = movies.iloc[idx]['title']
        scores[title] = float(score)

    return scores

# Test it
test_scores = get_content_scores('Avatar')
top5 = sorted(test_scores.items(), key=lambda x: x[1], reverse=True)[1:6]

print("✅ Content score function ready")
print("\nTop 5 content matches for Avatar:")
for title, score in top5:
    print(f"   {title:<45} score: {score:.4f}")

✅ Content score function ready

Top 5 content matches for Avatar:
   Aliens vs Predator: Requiem                   score: 0.2868
   Aliens                                        score: 0.2690
   Falcon Rising                                 score: 0.2605
   Independence Day                              score: 0.2556
   Titan A.E.                                    score: 0.2504

In [37]:
def get_collab_scores(user_id, n=50):
    """
    Returns a dictionary of {movie_title: collab_score}
    for top N movies based on ALS collaborative filtering.
    """
    user_id = int(user_id)

    if user_id not in user_to_idx:
        return {}

    user_idx = user_to_idx[user_id]

    rec_ids, scores = als_model.recommend(
        userid=user_idx,
        user_items=sparse_user_movie[user_idx],
        N=n,
        filter_already_liked_items=True
    )

    result = {}
    for movie_idx, score in zip(rec_ids, scores):
        movie_idx = int(movie_idx)
        if movie_idx not in idx_to_movie:
            continue
        ml_movie_id = idx_to_movie[movie_idx]
        row = tmdb_with_ml_id[tmdb_with_ml_id['movieId'] == ml_movie_id]
        if len(row) > 0:
            title = row['title'].values[0]
            result[title] = float(score)

    return result

# Test it
real_user = sorted(list(user_to_idx.keys()))[0]
test_collab = get_collab_scores(user_id=real_user, n=10)

print("✅ Collaborative score function ready")
print(f"\nTop collab picks for User {real_user}:")
for title, score in list(test_collab.items())[:5]:
    print(f"   {title:<45} score: {score:.4f}")

✅ Collaborative score function ready

Top collab picks for User 2:
   The Count of Monte Cristo                     score: 0.9774
   Dances with Wolves                            score: 0.8528
   Finding Nemo                                  score: 0.8379
   Chicken Run                                   score: 0.8203
   The Mask of Zorro                             score: 0.8095

In [38]:
def hybrid_recommend(movie_title, user_id=None, alpha=0.7, n=5):
    """
    Hybrid recommender combining content + collaborative filtering.
    
    Parameters:
    -----------
    movie_title : str   — movie the user selected
    user_id     : int   — logged in user (None = content only)
    alpha       : float — weight for content (0.7 = 70% content, 30% collab)
    n           : int   — number of recommendations to return

    Returns:
    --------
    DataFrame with title, content_score, collab_score, hybrid_score
    """

    # Step 1: Get content scores for all movies
    content_scores = get_content_scores(movie_title)

    if not content_scores:
        return pd.DataFrame({'error': [f'Movie "{movie_title}" not found']})

    # Step 2: Get collaborative scores if user is known
    collab_scores = {}
    if user_id is not None:
        collab_scores = get_collab_scores(user_id=user_id, n=100)

    # Step 3: Normalize content scores to 0-1 range
    max_content = max(content_scores.values()) if content_scores else 1
    min_content = min(content_scores.values()) if content_scores else 0
    range_content = max_content - min_content if max_content != min_content else 1

    # Step 4: Normalize collab scores to 0-1 range
    if collab_scores:
        max_collab   = max(collab_scores.values())
        min_collab   = min(collab_scores.values())
        range_collab = max_collab - min_collab if max_collab != min_collab else 1
    
    # Step 5: Combine scores
    all_titles = set(content_scores.keys())
    results    = []

    for title in all_titles:
        # Skip the selected movie itself
        if title == movie_title:
            continue

        # Normalized content score
        c_score = (content_scores.get(title, 0) - min_content) / range_content

        # Normalized collab score
        if collab_scores:
            raw_collab = collab_scores.get(title, 0)
            col_score  = (raw_collab - min_collab) / range_collab
        else:
            col_score = 0

        # Hybrid score
        if collab_scores:
            hybrid = alpha * c_score + (1 - alpha) * col_score
        else:
            hybrid = c_score  # content only if no user

        results.append({
            'title'         : title,
            'content_score' : round(c_score,  4),
            'collab_score'  : round(col_score, 4),
            'hybrid_score'  : round(hybrid,    4)
        })

    # Step 6: Sort by hybrid score and return top N
    results_df = (pd.DataFrame(results)
                  .sort_values('hybrid_score', ascending=False)
                  .head(n)
                  .reset_index(drop=True))

    return results_df

print("✅ hybrid_recommend function ready")

✅ hybrid_recommend function ready

In [39]:
print("=" * 60)
print("TEST 1 — Content Only (no user logged in)")
print("=" * 60)

recs = hybrid_recommend(
    movie_title='The Dark Knight',
    user_id=None,
    n=5
)
print(recs.to_string(index=False))

============================================================
TEST 1 — Content Only (no user logged in)
============================================================
                title  content_score  collab_score  hybrid_score
The Dark Knight Rises         0.4226             0        0.4226
        Batman Begins         0.4022             0        0.4022
       Batman Returns         0.3314             0        0.3314
       Batman Forever         0.2941             0        0.2941
       Batman & Robin         0.2601             0        0.2601

In [40]:
print("=" * 60)
print("TEST 2 — Hybrid (content + collaborative)")
print("=" * 60)

real_user = sorted(list(user_to_idx.keys()))[0]

recs = hybrid_recommend(
    movie_title='The Dark Knight',
    user_id=real_user,
    alpha=0.7,
    n=5
)
print(f"User ID: {real_user}")
print(recs.to_string(index=False))

============================================================
TEST 2 — Hybrid (content + collaborative)
============================================================
User ID: 2
                    title  content_score  collab_score  hybrid_score
The Count of Monte Cristo         0.1221        1.0000        0.3855
       Dances with Wolves         0.0695        0.7851        0.2842
        The Mask of Zorro         0.0741        0.7104        0.2650
             Finding Nemo         0.0401        0.7594        0.2559
      Catch Me If You Can         0.0940        0.6207        0.2520

In [41]:
print("=" * 60)
print("COMPARISON — Content Only vs Hybrid")
print("=" * 60)

real_user = sorted(list(user_to_idx.keys()))[0]

content_only = hybrid_recommend('Inception', user_id=None,      n=5)
hybrid_recs  = hybrid_recommend('Inception', user_id=real_user, n=5)

print("\n📽️  Content Only:")
for _, row in content_only.iterrows():
    print(f"   {row['title']:<40} {row['hybrid_score']:.4f}")

print(f"\n🤝 Hybrid (User {real_user}):")
for _, row in hybrid_recs.iterrows():
    print(f"   {row['title']:<40} {row['hybrid_score']:.4f}")

print("\n✅ Notice how hybrid results differ — personalized for the user!")

============================================================
COMPARISON — Content Only vs Hybrid
============================================================

📽️  Content Only:
   12 Rounds                                0.3037
   Abduction                                0.2795
   RED                                      0.2785
   Krrish                                   0.2747
   The Animal                               0.2746

🤝 Hybrid (User 2):
   The Count of Monte Cristo                0.4684
   The Mask of Zorro                        0.3494
   Finding Nemo                             0.3201
   Dances with Wolves                       0.3154
   My Cousin Vinny                          0.2895

✅ Notice how hybrid results differ — personalized for the user!

In [42]:
print("Evaluating hybrid system... (2-3 minutes)\n")

test_users = sorted(list(user_to_idx.keys()))[:100]
hits_content = 0
hits_hybrid  = 0
total        = 0

# Get movies list for testing
all_titles = movies['title'].tolist()

for uid in test_users:
    # Pick a random movie this user rated highly
    user_highly_rated = ratings_clean[
        (ratings_clean['userId'] == uid) &
        (ratings_clean['rating'] >= 4.0)
    ]

    if len(user_highly_rated) < 2:
        continue

    # Use first highly rated movie as input
    sample_movie_id = user_highly_rated.iloc[0]['movieId']
    sample_row      = tmdb_with_ml_id[
        tmdb_with_ml_id['movieId'] == sample_movie_id
    ]

    if len(sample_row) == 0:
        continue

    sample_title = sample_row['title'].values[0]
    if sample_title not in movies['title'].values:
        continue

    # Actual movies user liked (excluding input)
    actual_liked_ids = user_highly_rated.iloc[1:]['movieId'].tolist()
    actual_titles    = []
    for mid in actual_liked_ids:
        row = tmdb_with_ml_id[tmdb_with_ml_id['movieId'] == mid]
        if len(row) > 0:
            actual_titles.append(row['title'].values[0])

    if not actual_titles:
        continue

    # Content only recs
    content_recs = hybrid_recommend(
        sample_title, user_id=None, n=10
    )['title'].tolist()

    # Hybrid recs
    hybrid_recs_list = hybrid_recommend(
        sample_title, user_id=uid, n=10
    )['title'].tolist()

    hits_content += len(set(content_recs) & set(actual_titles))
    hits_hybrid  += len(set(hybrid_recs_list) & set(actual_titles))
    total        += 1

p_content = hits_content / (total * 10) if total > 0 else 0
p_hybrid  = hits_hybrid  / (total * 10) if total > 0 else 0

print("=" * 50)
print(f"📊 Hybrid System Evaluation")
print(f"   Content-Only Precision : {p_content:.4f} ({p_content*100:.1f}%)")
print(f"   Hybrid Precision       : {p_hybrid:.4f}  ({p_hybrid*100:.1f}%)")
print(f"   Improvement            : +{(p_hybrid-p_content)*100:.1f}%")
print(f"   Tested on              : {total} users")
print("=" * 50)

Evaluating hybrid system... (2-3 minutes)

==================================================
📊 Hybrid System Evaluation
   Content-Only Precision : 0.0450 (4.5%)
   Hybrid Precision       : 0.0020  (0.2%)
   Improvement            : +-4.3%
   Tested on              : 100 users
==================================================

In [43]:
pickle.dump(content_similarity, open('content_similarity.pkl', 'wb'))
pickle.dump(cv,                 open('count_vectorizer.pkl',   'wb'))

print("✅ content_similarity.pkl")
print("✅ count_vectorizer.pkl")
print("\n🎯 Phase 3 Complete!")
print("Share Cell 6, 7, 8 outputs + evaluation results!")
print("Then we move to Phase 4 — Streamlit UI upgrade! 🚀")

✅ content_similarity.pkl
✅ count_vectorizer.pkl

🎯 Phase 3 Complete!
Share Cell 6, 7, 8 outputs + evaluation results!
Then we move to Phase 4 — Streamlit UI upgrade! 🚀

In [44]:
from sentence_transformers import SentenceTransformer
import numpy as np
import pickle
import pandas as pd

# Load the BERT model
# 'all-MiniLM-L6-v2' is the perfect balance of speed and accuracy
# Used in production at many companies
print("Loading BERT model... (downloads ~90MB first time)")

bert_model = SentenceTransformer('all-MiniLM-L6-v2')

print("✅ BERT model loaded!")
print(f"Model: all-MiniLM-L6-v2")
print(f"Embedding size: 384 dimensions")

Loading BERT model... (downloads ~90MB first time)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

c:\ProgramData\anaconda3\envs\recommender\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ishas\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

✅ BERT model loaded!
Model: all-MiniLM-L6-v2
Embedding size: 384 dimensions

In [45]:
# Load movies dataframe
movies_dict = pickle.load(open('movie_dict.pkl', 'rb'))
movies_bert = pd.DataFrame(movies_dict)

# BERT works better with natural readable text
# Unlike TF-IDF, BERT understands meaning so we don't need stemming
# We'll use the raw tags but make them more readable

def prepare_bert_text(tags):
    """
    Convert tags string into clean readable text for BERT.
    BERT understands natural language better than stemmed words.
    """
    # Replace common concatenated words back to readable form
    text = tags.replace('ScienceFiction', 'Science Fiction')
    text = text.replace('cultureclash', 'culture clash')
    text = text.replace('spacewar', 'space war')
    text = text.replace('basedonnovel', 'based on novel')
    return text.lower().strip()

movies_bert['bert_text'] = movies_bert['tags'].apply(prepare_bert_text)

print("✅ Text prepared for BERT")
print(f"Total movies: {len(movies_bert)}")
print(f"\nSample text for Avatar:")
print(movies_bert[movies_bert['title'] == 'Avatar']['bert_text'].values[0][:200])

✅ Text prepared for BERT
Total movies: 4806

Sample text for Avatar:
in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cul

In [46]:
# This is the core step — BERT reads each movie's text
# and creates a 384-dimensional vector capturing semantic meaning

print("Generating BERT embeddings...")
print("This will take 3-8 minutes for 4800 movies\n")

texts = movies_bert['bert_text'].tolist()

# batch_size=64 processes 64 movies at once for speed
# show_progress_bar shows live progress
bert_embeddings = bert_model.encode(
    texts,
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True
)

print(f"\n✅ BERT embeddings generated!")
print(f"Shape: {bert_embeddings.shape}")
print(f"Meaning: {bert_embeddings.shape[0]} movies × {bert_embeddings.shape[1]} features")

Generating BERT embeddings...
This will take 3-8 minutes for 4800 movies

Batches:   0%|          | 0/76 [00:00<?, ?it/s]

✅ BERT embeddings generated!
Shape: (4806, 384)
Meaning: 4806 movies × 384 features

In [47]:
from sklearn.metrics.pairwise import cosine_similarity

print("Computing BERT similarity matrix...")

# Compute cosine similarity between all movie embeddings
bert_similarity = cosine_similarity(bert_embeddings)

print(f"✅ BERT similarity matrix built")
print(f"Shape: {bert_similarity.shape}")

# Quick sanity check
avatar_idx  = movies_bert[movies_bert['title'] == 'Avatar'].index[0]
dark_knight = movies_bert[movies_bert['title'] == 'The Dark Knight'].index[0]
inception   = movies_bert[movies_bert['title'] == 'Inception'].index[0]

print(f"\nSanity check — similarity scores for Avatar:")
print(f"  Avatar vs Dark Knight : {bert_similarity[avatar_idx][dark_knight]:.4f}")
print(f"  Avatar vs Inception   : {bert_similarity[avatar_idx][inception]:.4f}")
print(f"  Avatar vs Avatar      : {bert_similarity[avatar_idx][avatar_idx]:.4f} (should be 1.0)")

Computing BERT similarity matrix...
✅ BERT similarity matrix built
Shape: (4806, 4806)

Sanity check — similarity scores for Avatar:
  Avatar vs Dark Knight : 0.1845
  Avatar vs Inception   : 0.1427
  Avatar vs Avatar      : 1.0000 (should be 1.0)

In [48]:
def bert_recommend(movie_title, n=5):
    """
    Returns top N recommendations using BERT embeddings.
    Understands semantic meaning — not just keyword matching.
    """
    if movie_title not in movies_bert['title'].values:
        return pd.DataFrame({'error': [f'Movie not found: {movie_title}']})

    movie_idx = movies_bert[movies_bert['title'] == movie_title].index[0]
    distances = bert_similarity[movie_idx]

    # Sort by similarity score
    similar_indices = sorted(
        list(enumerate(distances)),
        key=lambda x: x[1],
        reverse=True
    )[1:n+1]  # skip index 0 (itself)

    results = []
    for idx, score in similar_indices:
        results.append({
            'title'      : movies_bert.iloc[idx]['title'],
            'bert_score' : round(float(score), 4)
        })

    return pd.DataFrame(results)

print("✅ bert_recommend function ready")

✅ bert_recommend function ready

In [49]:
# This comparison is very important for your resume
# It shows BERT understands MEANING, not just keywords

test_movies = ['The Dark Knight', 'Inception', 'Avatar', 'The Godfather']

for movie in test_movies:
    if movie not in movies_bert['title'].values:
        continue

    # TF-IDF recommendations (your original system)
    movie_idx    = movies[movies['title'] == movie].index[0]
    tfidf_scores = content_similarity[movie_idx]
    tfidf_top5   = sorted(
        list(enumerate(tfidf_scores)),
        key=lambda x: x[1],
        reverse=True
    )[1:6]
    tfidf_titles = [movies.iloc[i[0]]['title'] for i in tfidf_top5]

    # BERT recommendations
    bert_top5   = bert_recommend(movie, n=5)['title'].tolist()

    print(f"\n{'='*55}")
    print(f"Movie: {movie}")
    print(f"{'='*55}")
    print(f"{'TF-IDF':<30} {'BERT':<30}")
    print(f"{'-'*55}")
    for t, b in zip(tfidf_titles, bert_top5):
        print(f"{t:<30} {b:<30}")

=======================================================
Movie: The Dark Knight
=======================================================
TF-IDF                         BERT
-------------------------------------------------------
The Dark Knight Rises          Batman
Batman Begins                  Batman
Batman Returns                 Batman Begins
Batman Forever                 Batman Returns
Batman                         The Dark Knight Rises

=======================================================
Movie: Inception
=======================================================
TF-IDF                         BERT
-------------------------------------------------------
12 Rounds                      The Maze Runner
Abduction                      The Skeleton Key
RED                            Mission: Impossible II
Krrish                         Sinister
The Animal                     Conspiracy Theory

=======================================================
Movie: Avatar
=======================================================
TF-IDF                         BERT
-------------------------------------------------------
Aliens vs Predator: Requiem    Battle: Los Angeles
Aliens                         Interstellar
Falcon Rising                  Serenity
Independence Day               Battleship
Titan A.E.                     The Inhabited Island

=======================================================
Movie: The Godfather
=======================================================
TF-IDF                         BERT
-------------------------------------------------------
The Godfather: Part II         The Godfather: Part II
The Godfather: Part III        The Godfather: Part III
City By The Sea                Casino
Sexy Beast                     GoodFellas
Road to Perdition              City By The Sea

In [50]:
def hybrid_recommend_bert(movie_title, user_id=None,
                          alpha=0.5, beta=0.3, gamma=0.2, n=5):
    """
    Full 3-layer hybrid recommender:

    Score = alpha × BERT_score
           + beta  × TF-IDF_score  
           + gamma × Collab_score

    Parameters:
    -----------
    alpha : weight for BERT        (default 0.5)
    beta  : weight for TF-IDF      (default 0.3)
    gamma : weight for ALS collab  (default 0.2)

    Note: alpha + beta + gamma should = 1.0
    """
    # Validate weights
    assert abs(alpha + beta + gamma - 1.0) < 0.01, \
        "Weights must sum to 1.0"

    # --- BERT scores ---
    if movie_title not in movies_bert['title'].values:
        return pd.DataFrame({'error': ['Movie not found']})

    bert_idx    = movies_bert[movies_bert['title'] == movie_title].index[0]
    bert_scores_raw = bert_similarity[bert_idx]

    # --- TF-IDF scores ---
    if movie_title in movies['title'].values:
        tfidf_idx        = movies[movies['title'] == movie_title].index[0]
        tfidf_scores_raw = content_similarity[tfidf_idx]
    else:
        tfidf_scores_raw = np.zeros(len(movies_bert))

    # --- Collab scores ---
    collab_dict = {}
    if user_id is not None:
        collab_dict = get_collab_scores(user_id=user_id, n=200)

    # --- Normalize helpers ---
    def normalize(arr):
        mn, mx = arr.min(), arr.max()
        if mx == mn:
            return arr
        return (arr - mn) / (mx - mn)

    bert_norm  = normalize(bert_scores_raw)
    tfidf_norm = normalize(tfidf_scores_raw) \
                 if len(tfidf_scores_raw) == len(movies_bert) \
                 else np.zeros(len(movies_bert))

    if collab_dict:
        max_c = max(collab_dict.values())
        min_c = min(collab_dict.values())
        rng_c = max_c - min_c if max_c != min_c else 1

    # --- Combine scores ---
    results = []
    for idx in range(len(movies_bert)):
        title = movies_bert.iloc[idx]['title']
        if title == movie_title:
            continue

        b_score = float(bert_norm[idx])
        t_score = float(tfidf_norm[idx]) \
                  if idx < len(tfidf_norm) else 0.0

        if collab_dict and title in collab_dict:
            c_score = (collab_dict[title] - min_c) / rng_c
        else:
            c_score = 0.0

        if user_id is not None:
            final = alpha * b_score + beta * t_score + gamma * c_score
        else:
            # No user — split between BERT and TF-IDF only
            final = (alpha / (alpha + beta)) * b_score + \
                    (beta  / (alpha + beta)) * t_score

        results.append({
            'title'       : title,
            'bert_score'  : round(b_score, 4),
            'tfidf_score' : round(t_score, 4),
            'collab_score': round(c_score, 4),
            'final_score' : round(final,   4)
        })

    return (pd.DataFrame(results)
            .sort_values('final_score', ascending=False)
            .head(n)
            .reset_index(drop=True))

print("✅ hybrid_recommend_bert function ready")
print("   Layers: BERT (50%) + TF-IDF (30%) + ALS (20%)")

✅ hybrid_recommend_bert function ready
   Layers: BERT (50%) + TF-IDF (30%) + ALS (20%)

In [51]:
real_user = sorted(list(user_to_idx.keys()))[0]

print("=" * 60)
print("FULL 3-LAYER HYBRID TEST")
print("=" * 60)

test_movies = ['The Dark Knight', 'Inception', 'Avatar']

for movie in test_movies:
    print(f"\n🎬 Input movie : {movie}")
    print(f"👤 User        : {real_user}")
    print(f"{'-'*55}")

    recs = hybrid_recommend_bert(
        movie_title=movie,
        user_id=real_user,
        alpha=0.5,
        beta=0.3,
        gamma=0.2,
        n=5
    )

    print(f"{'Title':<35} {'BERT':>6} {'TFIDF':>6} "
          f"{'Collab':>7} {'Final':>6}")
    print("-" * 65)
    for _, row in recs.iterrows():
        print(f"{row['title']:<35} "
              f"{row['bert_score']:>6.3f} "
              f"{row['tfidf_score']:>6.3f} "
              f"{row['collab_score']:>7.3f} "
              f"{row['final_score']:>6.3f}")

============================================================
FULL 3-LAYER HYBRID TEST
============================================================

🎬 Input movie : The Dark Knight
👤 User        : 2
-------------------------------------------------------
Title                                 BERT  TFIDF  Collab  Final
-----------------------------------------------------------------
Batman                               0.780  0.261   0.178  0.504
Batman                               0.767  0.277   0.178  0.502
Batman Begins                        0.742  0.402   0.000  0.492
The Dark Knight Rises                0.726  0.423   0.000  0.490
Batman Returns                       0.728  0.331   0.000  0.463

🎬 Input movie : Inception
👤 User        : 2
-------------------------------------------------------
Title                                 BERT  TFIDF  Collab  Final
-----------------------------------------------------------------
The Count of Monte Cristo            0.264  0.240   1.000  0.404
Good Will Hunting                    0.472  0.080   0.688  0.397
Catch Me If You Can                  0.431  0.123   0.686  0.390
Mission: Impossible II               0.552  0.153   0.309  0.384
Dances with Wolves                   0.308  0.114   0.822  0.352

🎬 Input movie : Avatar
👤 User        : 2
-------------------------------------------------------
Title                                 BERT  TFIDF  Collab  Final
-----------------------------------------------------------------
Independence Day                     0.510  0.256   0.427  0.417
Serenity                             0.568  0.145   0.310  0.389
The Last of the Mohicans             0.381  0.158   0.685  0.375
Titan A.E.                           0.542  0.250   0.102  0.366
Battle: Los Angeles                  0.580  0.245   0.000  0.364

In [52]:
# Save BERT embeddings and similarity matrix
np.save('bert_embeddings.npy', bert_embeddings)
pickle.dump(bert_similarity, open('bert_similarity.pkl', 'wb'))
pickle.dump(movies_bert.to_dict(), open('movies_bert_dict.pkl', 'wb'))

print("✅ bert_embeddings.npy")
print("✅ bert_similarity.pkl")
print("✅ movies_bert_dict.pkl")
print("\n🎯 Phase 4 Complete!")

✅ bert_embeddings.npy
✅ bert_similarity.pkl
✅ movies_bert_dict.pkl

🎯 Phase 4 Complete!